# SDLReader Docker Development Environment for TG5040
# For Docker-specific build tasks, see Makefile.docker
services:
  dev:
    image: ghcr.io/loveretro/tg5040-toolchain:latest
    pull_policy: always
    volumes:
      - ../../:/workspace
    stdin_open: true
    tty: true
